config/routes.rb
FinePrint::Engine.routes.draw do
  root to: 'home#index'

  resources :contracts do
    resources :signatures, only: [:index, :new, :create, :destroy],
                           shallow: true

    member do
      post :new_version
      put :publish
      put :unpublish
    end
  end
end

app/models/fine_print/contract.rb
module FinePrint
  class Contract < ActiveRecord::Base
    has_many :signatures, dependent: :destroy, inverse_of: :contract

    has_many :same_name, class_name: 'Contract',
             primary_key: :name, foreign_key: :name

    before_validation :downcase_name
    before_update :no_signatures
    before_destroy :no_signatures

    validates :name, presence: true, format: /\A[\w-]+\z/
    validates :title, presence: true
    validates :content, presence: true
    validates :version, uniqueness: { scope: :name, case_sensitive: false },
                        allow_nil: true

    default_scope -> { order(:name, version: :desc) }

    scope :published, -> { where.not(version: nil) }
    scope :latest, -> do
      fpc = arel_table
      sn = Arel::Table.new(:same_names_fine_print_contracts)
      joins(:same_name).group(:id).having(fpc[:version].eq(sn[:version].maximum))
    end
    scope :signed_by, ->(user) do
      joins(:signatures).where(fine_print_signatures: { user_id: user.id, user_type: class_name_for(user) })
    end

    def is_published?
      !version.nil?
    end

    def is_latest?
      is_published? && self == same_name.published.first
    end

    def signed_by?(user)
      user_class_name = self.class.class_name_for(user)
      signatures.loaded? ?
        signatures.any? do |signature|
          signature.user_id == user.id and signature.user_type == user_class_name
        end : signatures.where(user_id: user.id, user_type: user_class_name).exists?
    end

    def publish
      errors.add(:base, I18n.t('fine_print.contract.errors.already_published')) \
        if is_published?
      return false unless errors.empty?

      self.version = (same_name.published.first.try(:version) || 0) + 1

      save.tap do |success|
        instance_exec(self, &FinePrint.config.contract_published_proc) if success
      end
    end

    def unpublish
      errors.add(:base, I18n.t('fine_print.contract.errors.not_latest')) \
        unless is_latest?
      return false unless errors.empty?

      self.version = nil
      save
    end

    def new_version
      Contract.where(name: name, version: nil).first || \
        dup.tap{|contract| contract.version = nil}
    end

    ##############
    # Validation #
    ##############

    def no_signatures
      return if signatures.empty?
      errors.add(:base, I18n.t('fine_print.contract.errors.already_signed'))
      throw :abort
    end

    protected

    def downcase_name
      self.name = name.try(:downcase)
    end

    def self.class_name_for(user)
      user.class.base_class.name
    end
  end
end

app/models/fine_print/signature.rb
module FinePrint
  class Signature < ActiveRecord::Base
    belongs_to :contract, inverse_of: :signatures
    belongs_to :user, polymorphic: true

    before_update { false } # no changes allowed

    validate :contract_published, on: :create

    validates :contract, presence: true
    validates :contract_id, uniqueness: { scope: [:user_type, :user_id] }
    validates :user, presence: true

    default_scope { order(:contract_id, :user_type, :user_id) }

    def is_explicit?
      !is_implicit?
    end

    protected

    ##############
    # Validation #
    ##############

    def contract_published
      return if contract.is_published?
      errors.add(
        :contract, I18n.t('fine_print.signature.errors.contract.not_published')
      )
      throw :abort
    end
  end
end

app/controllers/fine_print/application_controller.rb
require 'responders'

module FinePrint
  class ApplicationController < ::ActionController::Base
    respond_to :html

    before_action :get_user, :can_manage

    layout FinePrint.config.layout

    helper FinePrint.config.helpers

    FinePrint.config.concerns.each do |concern|
      include concern
    end

    protected

    def get_user
      @user = instance_exec &FinePrint.config.current_user_proc
    end

    def can_manage
      instance_exec @user, &FinePrint.config.authenticate_manager_proc
    end
  end
end

app/controllers/fine_print/contracts_controller.rb
module FinePrint
  class ContractsController < FinePrint::ApplicationController
    include FinePrint::ApplicationHelper

    before_action :get_contract, except: [:index, :new, :create]

    def index
      @contracts = Contract.select(
        <<~EOS
          "fine_print_contracts".*, (
            SELECT COUNT(*) FROM "fine_print_signatures"
            WHERE "fine_print_signatures"."contract_id" = "fine_print_contracts"."id"
          ) AS "signatures_count"
        EOS
      ).all.to_a.group_by(&:name)
    end

    def new
      @contract = Contract.new
    end

    def create
      @contract = Contract.new
      @contract.name = params[:contract][:name]
      @contract.title = params[:contract][:title]
      @contract.content = params[:contract][:content]

      if @contract.save
        redirect_to @contract, notice: t('fine_print.contract.notices.created')
      else
        render action: 'new', alert: merge_errors_for(@contract)
      end
    end

    def show
    end

    def edit
      @contract.no_signatures
      redirect_to contracts_path, alert: merge_errors_for(@contract) \
        unless @contract.errors.empty?
    end

    def update
      @contract.name = params[:contract][:name]
      @contract.title = params[:contract][:title]
      @contract.content = params[:contract][:content]

      if @contract.save
        redirect_to @contract, notice: t('fine_print.contract.notices.updated')
      else
        render action: 'edit', alert: merge_errors_for(@contract)
      end
    end

    def destroy
      if @contract.destroy
        redirect_to contracts_path,
                    notice: t('fine_print.contract.notices.deleted')
      else
        redirect_to contracts_path, alert: merge_errors_for(@contract)
      end
    end

    def publish
      if @contract.publish
        redirect_to contracts_path,
                    notice: t('fine_print.contract.notices.published')
      else
        redirect_to contracts_path, alert: merge_errors_for(@contract)
      end
    end

    def unpublish
      if @contract.unpublish
        redirect_to contracts_path,
                    notice: t('fine_print.contract.notices.unpublished')
      else
        redirect_to contracts_path, alert: merge_errors_for(@contract)
      end
    end

    def new_version
      @contract = @contract.new_version
    end

    protected

    def get_contract
      @contract = Contract.find(params[:id])
    end
  end
end

app/controllers/fine_print/home_controller.rb
module FinePrint
  class HomeController < FinePrint::ApplicationController

    def index
      redirect_to contracts_path
    end

  end
end

app/controllers/fine_print/signatures_controller.rb
module FinePrint
  class SignaturesController < FinePrint::ApplicationController
    include FinePrint::ApplicationHelper

    skip_before_action :can_manage, only: [:new, :create]
    fine_print_skip only: [:new, :create]
    before_action :can_sign, only: [:new, :create]
    before_action :get_contract, only: [:index, :new, :create]

    def index
      @signatures = @contract.signatures
    end

    def new
      @signature = Signature.new
    end

    def create
      @signature = Signature.new

      unless params[:signature_accept]
        @signature.errors.add(
          :contract, t('fine_print.signature.errors.contract.must_agree')
        )
        render action: 'new'
        return
      end

      @signature.user = @user
      @signature.contract = @contract

      if @signature.save
        fine_print_return
      else
        render action: 'new', alert: merge_errors_for(@signature)
      end
    end

    def destroy
      @signature = Signature.find(params[:id])

      @signature.destroy
      redirect_to contract_signatures_path(@signature.contract),
                  notice: t('fine_print.signature.notices.deleted')
    end

    protected

    def can_sign
      instance_exec @user, &FinePrint.config.authenticate_user_proc
    end

    def get_contract
      @contract = Contract.find(params[:contract_id])
    end
  end
end

app/helpers/fine_print/application_helper.rb
module FinePrint
  module ApplicationHelper
    def merge_errors_for(obj)
      "#{obj.errors.collect{|f,e| "#{e}"}.join('. ')}."
    end
  end
end

app/views/fine_print/contracts/_form.html.erb
<%= form_for(@contract, html: { class: 'fine_print' }) do |f| %>
  <% if @contract.errors.any? %>
    <div id='error_explanation' class='fine_print errors'>
      <h4 class='fine_print heading'>
        <%= t 'fine_print.error', count: @contract.errors.count %>
      </h4>

      <ul>
      <% @contract.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :name, class: 'fine_print' %>
    <%= f.text_field :name, size: 40, class: 'fine_print text_field' %>
    <div class='fine_print field_description'>
      <%= t 'fine_print.contract.descriptions.name' %>
    </div>
  </div>
  <div class='field'>
    <%= f.label :title, class: 'fine_print' %>
    <%= f.text_field :title, size: 40, class: 'fine_print text_field' %>
    <div class='fine_print field_description'>
      <%= t 'fine_print.contract.descriptions.title' %>
    </div>
  </div>
  <div class='field'>
    <%= f.label :content, class: 'fine_print' %>
    <%= f.text_area :content, cols: 56, class: 'fine_print text_area' %>
  </div>
  <div class='field'>
    <%= f.label :is_signed_by_proxy, class: 'fine_print' %>
    <%= f.check_box :is_signed_by_proxy, class: 'fine_print check_box' %>
  </div>
  <br>

  <div class='actions'>
    <%= f.submit nil, class: 'fine_print submit' %>
  </div>
<% end %>

app/views/fine_print/contracts/_show.html.erb
<%# Clients of this partial must provide the following variable:
    contract %>

<h2 class='fine_print heading'><%= contract.title %> (<%= contract.version ? \
  t('fine_print.contract.status.version', version: contract.version.to_s) : \
  t('fine_print.contract.status.draft') %>)</h2>

<h4 class='fine_print heading'><%= t('fine_print.contract.status.updated_at', \
  updated_at: l(contract.updated_at, format: :fine_print)) %></h4>

<h4 class='fine_print heading'>
  <%= contract.is_signed_by_proxy? ?
    t('fine_print.contract.status.signed_by_proxy.is') :
    t('fine_print.contract.status.signed_by_proxy.is_not')
  %>
</h4>

<div class='fine_print contract'>
  <pre><%= @contract.content.html_safe %></pre>
</div>

app/views/fine_print/contracts/edit.html.erb
<h1 class='fine_print heading'><%= t 'fine_print.contract.actions.editing',
                                     contract: @contract.title.to_s %></h1>

<div class='fine_print edit_contract'>
  <%= render 'form' %>

  <br>

  <div class='fine_print links'>
    <%= link_to t('fine_print.contract.actions.show'), @contract,
                class: 'fine_print link' %> |
    <%= link_to t('fine_print.contract.actions.list'), contracts_path,
                class: 'fine_print link' %>
  </div>
</div>

app/views/fine_print/contracts/index.html.erb
<h1 class='fine_print heading'><%= t 'fine_print.contract.status.index' %></h1>

<div class='fine_print contract_index'>

  <% @contracts.each do |name, contracts| %>

    <%# Sort contracts by version number; unpublished contracts go at end by creation date %>
    <% #contracts = contracts.sort_by {|cc| cc.version || cc.created_at.to_i} %>

    <ul class='fine_print'>
      <li><%= name %></li>

        <ul class='fine_print'>
          <% contracts.each do |contract| %>
            <li><%= link_to contract.title, contract, class: 'fine_print link' %>
              (<%= contract.version.nil? ? \
                   t('fine_print.contract.status.draft') : \
                   t('fine_print.contract.status.version',
                     version: contract.version.to_s) %>)
              <% if contract.signatures_count == 0 %>
                [<%= link_to t('fine_print.contract.actions.edit'),
                             edit_contract_path(contract),
                             class: 'fine_print link' %>]
                <% if contract.is_published? %>
                  [<%= link_to(
                    t('fine_print.contract.actions.unpublish'),
                    unpublish_contract_path(contract),
                    method: :put,
                    data: {
                      confirm: t('fine_print.contract.actions.confirm.unpublish')
                    },
                    class: 'fine_print link'
                  ) %>]
                <% else %>
                  [<%= link_to(
                    t('fine_print.contract.actions.publish'),
                    publish_contract_path(contract),
                    method: :put,
                    data: {
                      confirm: t('fine_print.contract.actions.confirm.publish')
                    },
                    class: 'fine_print link'
                  ) %>]
                <% end %>
                [<%= link_to(
                  t('fine_print.contract.actions.delete'),
                  contract,
                  method: :delete,
                    data: {
                      confirm: t('fine_print.contract.actions.confirm.delete')
                    },
                  class: 'fine_print link'
                ) %>]
              <% else %>
                [<%= link_to t('fine_print.contract.actions.new_version'),
                             new_version_contract_path(contract),
                             method: :post,
                             class: 'fine_print link' %>]
                [<%= link_to t('fine_print.contract.actions.signatures'),
                             contract_signatures_path(contract),
                             class: 'fine_print link' %>]
              <% end %>
            </li>
          <% end %>
        </ul>

    </ul>

  <% end %>

  <div class='fine_print links'>
    <%= link_to 'New Contract', new_contract_path, class: 'fine_print link' %>
  </div>

</div>

app/views/fine_print/contracts/new.html.erb
<h1 class='fine_print heading'><%= t('fine_print.contract.actions.new') %></h1>

<div class='fine_print new_contract'>
  <%= render 'form' %>

  <br>

  <div class='fine_print links'>
    <%= link_to t('fine_print.contract.actions.list'),
                contracts_path,
                class: 'fine_print link' %>
  </div>
</div>

app/views/fine_print/contracts/new_version.html.erb
<h1 class='fine_print heading'>
  <%= t('fine_print.contract.actions.new_version_of',
      contract: @contract.name) %>
</h1>

<div class='fine_print new_contract_version'>
  <%= render 'form' %>

  <br>

  <div class='fine_print links'>
    <%= link_to t('fine_print.contract.actions.list'),
                contracts_path,
                class: 'fine_print link' %>
  </div>
</div>

app/views/fine_print/contracts/show.html.erb
<h1 class='fine_print heading'><%= t('fine_print.contract.actions.show') %></h1>

<br>

<h4 class='fine_print heading'><%= t('fine_print.contract.status.name',
                                   name: @contract.name) %></h4>

<%= render partial: 'show', locals: { contract: @contract } %>

<br>

<div class='fine_print links'>
  <% if @contract.signatures.empty? %>
    <%= link_to t('fine_print.contract.actions.edit'),
                edit_contract_path(@contract),
                class: 'fine_print link' %> |
      <% if @contract.is_published? %>
        <%= link_to t('fine_print.contract.actions.unpublish'),
                    unpublish_contract_path(@contract),
                    method: :put,
                    data: {
                      confirm: t('fine_print.contract.actions.confirm.unpublish')
                    },
                    class: 'fine_print link' %>
      <% else %>
        <%= link_to t('fine_print.contract.actions.publish'),
                    publish_contract_path(@contract),
                    method: :put,
                    data: {
                      confirm: t('fine_print.contract.actions.confirm.publish')
                    },
                    class: 'fine_print link' %> |
      <% end %>
      <%= link_to t('fine_print.contract.actions.delete'),
                  @contract,
                  method: :delete,
                  data: {
                    confirm: t('fine_print.contract.actions.confirm.delete')
                  },
                  class: 'fine_print link' %>
  <% else %>
    <%= link_to t('fine_print.contract.actions.new_version'),
                new_version_contract_path(@contract),
                method: :post,
                class: 'fine_print link' %> |
    <%= link_to t('fine_print.contract.actions.signatures'),
                contract_signatures_path(@contract),
                class: 'fine_print link' %>
  <% end %>
  | <%= link_to t('fine_print.contract.actions.list'),
                contracts_path,
                class: 'fine_print link' %>
</div>

app/views/fine_print/signatures/_form.html.erb
<%= form_for([@contract, @signature], html: { class: 'fine_print' }) do |f| %>
  <% if @signature.errors.any? %>
    <div id='error_explanation' class='fine_print errors'>
      <h4 class='fine_print heading'>
        <%= t 'fine_print.error', count: @signature.errors.count %>
      </h4>

      <ul>
        <% @signature.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :accept,
                t('fine_print.signature.actions.accept'),
                class: 'fine_print' %>
    <%= check_box_tag :signature_accept, class: 'fine_print check_box' %>
  </div>

  <br>

  <div class='actions'>
    <%= f.submit t('fine_print.signature.actions.sign'),
                 class: 'fine_print submit',
                 data: { disable_with: 'Please wait...' } %>
  </div>
<% end %>

app/views/fine_print/signatures/index.html.erb
<h1 class='fine_print heading'>
  <%= t('fine_print.signature.status.for_contract',
        contract: link_to(
          "#{@contract.title} #{t('fine_print.contract.status.version',
                                version: @contract.version.to_s)}",
          @contract
        )
      ).html_safe %>
</h1>

<div class='fine_print signature_index'>

  <table class='fine_print top_heading index'>
    <tr class='fine_print heading-row'>
      <th><%= t 'activerecord.attributes.fine_print/signature.user_type' %>&nbsp;</th>
      <th>&nbsp;<%= t 'activerecord.attributes.fine_print/signature.user_id' %>&nbsp;</th>
      <th>&nbsp;<%= t 'activerecord.attributes.fine_print/signature.created_at' %>&nbsp;</th>
      <th>&nbsp;<%= t 'activerecord.attributes.fine_print/signature.is_implicit' %>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>

  <% @signatures.each do |signature| %>
    <tr class='fine_print data-row <%= cycle('even', 'odd') %>'>
      <td><%= signature.user_type %>&nbsp;</td>
      <td>&nbsp;<%= signature.user_id %>&nbsp;</td>
      <td>&nbsp;<%= l signature.created_at, format: :fine_print %>&nbsp;</td>
      <td>&nbsp;<%= t signature.is_implicit?.to_s %>&nbsp;</td>
      <td>&nbsp;<%= link_to(
                      t('fine_print.signature.actions.delete'),
                      signature,
                      method: :delete,
                      data: {
                        confirm: t('fine_print.signature.actions.confirm.delete')
                      },
                      class: 'fine_print link'
                    ) %>
      </td>
    </tr>
  <% end %>
  </table>

  <br>

  <div class='fine_print links'>
    <%= link_to t('fine_print.contract.actions.list'), contracts_path,
                class: 'fine_print link' %>
  </div>

</div>

app/views/fine_print/signatures/new.html.erb
<% if FinePrint.signed_any_version_of_contract?(@user, @contract) %>
  <div class='fine_print notice'>
    <h4 class='fine_print heading'>
      <%= t('fine_print.signature.status.new_version',
            contract: @contract.title) %>
    </h4>
  </div>
<% end %>

<div class='fine_print contract'>
  <%= render partial: 'fine_print/contracts/show',
             locals: { contract: @contract } %>
</div>

<div class='fine_print new_signature'>
  <%= render 'form' %>
</div>